// 32 structure/plan lessons (all lines from the start position, real theory).
export const PLANS = [
  { id: 'm-plan-stonewall-w', title: 'Stonewall Attack (White)', level: 'Beginner', hero: 'w',
    tagline: 'Build the c3-d4-e3-f4 wall and storm.',
    desc: 'The club steamroller: pawns on c3-d4-e3-f4 control everything, the dark bishop goes to d3, and White attacks with Ne5 and Qh5 ideas.',
    ideas: ['f4 is safe once e3 and d4 back it.', 'Ne5 is the dream outpost — support it.', 'Attack with Qh5 and Bxh7+ sacrifices.'],
    line: ['d2d4','d7d5','e2e3','g8f6','f1d3','e7e6','f2f4','c7c5','c2c3','b8c6','g1f3','f8d6','e1g1','e8g8'],
    notes: { 13: 'Both sides castle — White’s storm is ready.' },
    drill: { afterPly: 10, moves: ['g1f3','f8d6','e1g1'], about: 'White to play: develop and castle!' } },
  { id: 'm-plan-stonewall-b', title: 'Stonewall Dutch (Black)', level: 'Intermediate', hero: 'b',
    tagline: 'The concrete wall: c6-d5-e6-f5.',
    desc: 'Black’s Stonewall clamps the center with four pawns and dreams of ...Ne4 outposts. White can barely move a piece.',
    ideas: ['c6-d5-e6-f5: nothing passes.', '...Ne4 is worth a piece — White must trade it.', 'Attack with ...Qh5 and ...g5 breaks.'],
    line: ['d2d4','d7d5','c2c4','e7e6','b1c3','c7c6','e2e3','f7f5','g1f3','g8f6','f1d3','f8d6','e1g1'],
    notes: { 7: '3...f5! The wall goes up at once.' },
    drill: { afterPly: 11, moves: ['f8d6','e1g1'], about: 'Black to move: develop and castle!' } },
  { id: 'm-plan-hedgehog', title: 'Hedgehog System', level: 'Advanced', hero: 'b',
    tagline: 'Spines out: ...a6, ...d6, ...e6 and wait.',
    desc: 'The Hedgehog concedes space for flexibility: pawns on a6-d6-e6, bishops behind them, then ...b5 or ...d5 breaks at the perfect moment.',
    ideas: ['Stay compact — breaks come later (...b5!).', 'Knights belong on c5 and e5.', 'Trade White’s binders, never the spines.'],
    line: ['c2c4','c7c5','g1f3','g8f6','d2d4','c5d4','f3d4','e7e6','b1c3','d7d6','g2g3','a7a6','f1g2','f8e7','e2e4'],
    notes: { 11: '6...a6! The spines are out.' },
    drill: { afterPly: 13, moves: ['f8e7','e2e4'], about: 'Black to move: finish and push!' } },
  { id: 'm-plan-english-botvinnik', title: "English: Botvinnik System", level: 'Intermediate', hero: 'w',
    tagline: 'c4-e4 pawn duo with fianchetto pressure.',
    desc: 'Botvinnik’s English: a broad center with c4 and e4, knights eyeing d5, and kingside expansion with f4 to come.',
    ideas: ['c4+e4 duo controls d5 forever.', 'Nb6 is misplaced — punish it with d4.', 'Expand with Rb1 and b4 when ready.'],
    line: ['c2c4','e7e5','b1c3','g8f6','g1f3','b8c6','g2g3','d7d5','c4d5','f6d5','f1g2','d5b6'],
    notes: { 11: '6...Nb6? Misplaced — d4! comes next.' },
    drill: { afterPly: 10, moves: ['f1g2','d5b6'], about: 'White to play: develop with gain!' } },
  { id: 'm-plan-english-kid', title: 'English vs King’s Indian', level: 'Intermediate', hero: 'w',
    tagline: 'Double fianchetto squeeze.',
    desc: 'The quiet English crush: both bishops fianchettoed, Black has no breaks, and White improves forever with Rb1 and d4.',
    ideas: ['No ...d5? No ...e5? Then squeeze.', 'Rb1 prepares the b4 break.', 'Trade into a better endgame anytime.'],
    line: ['c2c4','g8f6','b1c3','g7g6','g2g3','f8g7','f1g2','e8g8','g1f3','d7d6','e1g1','e7e5'],
    notes: { 11: '6...e5? gives White d5 — squeeze instead.' },
    drill: { afterPly: 10, moves: ['e1g1','e7e5'], about: 'Castle, then squeeze!' } },
  { id: 'm-plan-kid-bayonet', title: 'KID: Bayonet Attack', level: 'Advanced', hero: 'w',
    tagline: '9.b4! space on the queenside first.',
    desc: 'The Bayonet stabs ...a5 ideas before Black starts: 9.b4 grabs queenside space and threatens b5, slowing all counterplay.',
    ideas: ['9.b4! stops ...a5 and eyes b5.', 'Black’s ...Nh5 comes too slow now.', 'Follow with Nd2-f1-g3 and f4.'],
    line: ['d2d4','g8f6','c2c4','g7g6','b1c3','f8g7','e2e4','d7d6','g1f3','e8g8','f1e2','e7e5','e1g1','b8c6','d4d5','c6e7','b2b4','f6h5'],
    notes: { 16: '9.b4! The bayonet — queenside first.' },
    drill: { afterPly: 16, moves: ['b2b4','f6h5'], about: 'White to play: the Bayonet!' } },
  { id: 'm-plan-grunfeld-ex', title: 'Grünfeld Exchange Plans', level: 'Advanced', hero: 'w',
    tagline: 'Big center vs piece pressure.',
    desc: 'White builds the full center and Black attacks it from afar. The whole Grünfeld debate: can the center move, or will ...c5 destroy it?',
    ideas: ['e4+d4+c3: the Nachtigal center.', '...c5! is the thematic destroyer.', 'Castle long and push — or get pushed.'],
    line: ['d2d4','g8f6','c2c4','g7g6','b1c3','d7d5','c4d5','f6d5','e2e4','d5c3','b2c3','f8g7','f1c4','c7c5'],
    notes: { 13: '7...c5! Thematic — blast the center.' },
    drill: { afterPly: 12, moves: ['f1c4','c7c5'], about: 'Develop, then face ...c5!' } },
  { id: 'm-plan-grunfeld-russian', title: 'Grünfeld Russian System', level: 'Advanced', hero: 'w',
    tagline: 'Qb3 pressures d5 and b7.',
    desc: 'The Russian avoids the big center: Qb3 hits d5 and b7, White keeps flexible development and a safe king.',
    ideas: ['Qb3 double-attacks before committing.', 'e4 comes only with backup.', '...a6 prepares ...b5 counterplay.'],
    line: ['d2d4','g8f6','c2c4','g7g6','b1c3','d7d5','g1f3','f8g7','d1b3','d5c4','b3c4','e8g8','e2e4','a7a6'],
    notes: { 8: '4.Qb3! No big center, no problems.' },
    drill: { afterPly: 12, moves: ['e2e4','a7a6'], about: 'Push with backup!' } },
  { id: 'm-plan-catalan-closed', title: 'Catalan: Closed Squeeze', level: 'Advanced', hero: 'w',
    tagline: 'g3-Bg2 pressure without risk.',
    desc: 'The Catalan mixes Queen’s Gambit space with a fianchetto: Black holds c4 for a while, but Qc2 and a4 always win it back with pressure.',
    ideas: ['Qc2 eyes c4 and h7 together.', 'a4! undermines ...b5 holders.', 'The g2-bishop never moves — it rules.'],
    line: ['d2d4','g8f6','c2c4','e7e6','g2g3','d7d5','f1g2','f8e7','g1f3','e8g8','e1g1','d5c4','d1c2','a7a6'],
    notes: { 12: '7.Qc2! The pawn comes back with interest.' },
    drill: { afterPly: 12, moves: ['d1c2','a7a6'], about: 'White to play: Qc2!' } },
  { id: 'm-plan-catalan-open', title: 'Catalan: Open Lines', level: 'Advanced', hero: 'w',
    tagline: 'Qa4+ wins the pawn back at once.',
    desc: 'Black grabs c4 early and White answers Qa4+: check, develop, and regain the pawn before Black castles.',
    ideas: ['5.Qa4+! Check first, pawn second.', '...Nbd7 blocks but concedes tempo.', 'Open diagonals favor the bishops.'],
    line: ['d2d4','g8f6','c2c4','e7e6','g2g3','d7d5','f1g2','d5c4','d1a4','b8d7','a4c4'],
    notes: { 8: '5.Qa4+! The instant refund.' },
    drill: { afterPly: 8, moves: ['d1a4','b8d7','a4c4'], about: 'White to play: win it back!' } },
  { id: 'm-plan-slav-chebanenko', title: 'Chebanenko Slav', level: 'Intermediate', hero: 'b',
    tagline: '4...a6 keeps every option.',
    desc: 'The modern Slav: ...a6 prepares ...b5 without committing the bishop, keeping ...dxc4 and ...e6 both alive.',
    ideas: ['...a6 first, decide later.', '...b5! comes with tempo on c4.', 'The c8-bishop stays home until it’s good.'],
    line: ['d2d4','d7d5','c2c4','c7c6','g1f3','g8f6','b1c3','a7a6','e2e3','b7b5','b2b4'],
    notes: { 9: '5...b5! Space with tempo.' },
    drill: { afterPly: 9, moves: ['b7b5','b2b4'], about: 'Black to move: ...b5!' } },
  { id: 'm-plan-slav-main', title: 'Slav Main Line Plans', level: 'Intermediate', hero: 'b',
    tagline: 'Take on c4, hold with ...b5.',
    desc: 'The classical Slav: grab c4, play ...Bf5 before ...e6 (no locked bishop!), and hold the pawn with ...b5.',
    ideas: ['...dxc4 first — ask questions later.', '...Bf5 BEFORE ...e6 always.', '...b5-a5 holds everything.'],
    line: ['d2d4','d7d5','c2c4','c7c6','g1f3','g8f6','b1c3','d5c4','a2a4','c8f5','e2e3','e7e6','f1c4','f8b4','e1g1'],
    notes: { 9: '5...Bf5! Out before the wall.' },
    drill: { afterPly: 13, moves: ['f8b4','e1g1'], about: 'Black to move: pin, White castles!' } },
  { id: 'm-plan-caro-panov', title: 'Panov-Botvinnik Plans', level: 'Intermediate', hero: 'w',
    tagline: 'Isolated queen pawn — attack!',
    desc: 'The Panov gives White the IQP attacking setup: open c/e-files, d5 outpost dreams, and a kingside attack before Black blockades.',
    ideas: ['c4! creates the IQP structure.', 'Attack — endgames favor Black.', 'd5 is yours if Black blinks.'],
    line: ['e2e4','c7c6','d2d4','d7d5','e4d5','c6d5','c2c4','g8f6','b1c3','e7e6','g1f3','f8b4'],
    notes: { 6: '4.c4! The IQP is born.' },
    drill: { afterPly: 10, moves: ['g1f3','f8b4'], about: 'Develop for the attack!' } },
  { id: 'm-plan-french-tarrasch', title: 'French Tarrasch Plans', level: 'Intermediate', hero: 'w',
    tagline: 'Nd2 keeps options, Bc4 eyes f7.',
    desc: 'The Tarrasch avoids Winawer pins: Nd2 supports e4 and c4 breaks, Bc4 pressures f7, and Black’s ...c5 always comes.',
    ideas: ['Nd2 over Nc3 — no pins allowed.', 'Meet ...c5 with exd5 pressure.', 'Bc4-f7 ideas never go away.'],
    line: ['e2e4','e7e6','d2d4','d7d5','b1d2','c7c5','e4d5','d8d5','g1f3','c5d4','f1c4','d5d6'],
    notes: { 4: '3.Nd2! Flexible and pin-proof.' },
    drill: { afterPly: 10, moves: ['f1c4','d5d6'], about: 'Eye f7!' } },
  { id: 'm-plan-french-steinitz', title: 'French Steinitz Attack', level: 'Intermediate', hero: 'w',
    tagline: 'Bg5 pins before Black settles.',
    desc: '3.Nc3 Nf6 4.Bg5 pins before ...Be7 comfort: double Black’s f-pawns or win the bishop pair with Bxf6.',
    ideas: ['Bg5 first — questions later.', 'Bxf6 doubles pawns when good.', 'e5 wedge follows with f4.'],
    line: ['e2e4','e7e6','d2d4','d7d5','b1c3','g8f6','c1g5','f8e7'],
    notes: { 6: '4.Bg5! The pin comes early.' },
    drill: { afterPly: 6, moves: ['c1g5','f8e7'], about: 'White to play: the pin!' } },
  { id: 'm-plan-iqp-white', title: 'IQP: White Attacks', level: 'Advanced', hero: 'w',
    tagline: 'Your isolani must attack.',
    desc: 'Mirror of the black IQP: White’s d4-isolani gives e5/c5 squares and open files. Push d5 or attack — never defend passively.',
    ideas: ['d5! is the freeing break — time it.', 'Rooks to c1/e1 before pushing.', 'Trade into attack, never into defense.'],
    line: ['d2d4','d7d5','c2c4','e7e6','g1f3','g8f6','e2e3','f8e7','f1d3','e8g8','e1g1','c7c5','c4d5','e6d5','d4c5','e7c5'],
    notes: { 15: '8.dxc5 isolates — now attack!' },
    drill: { afterPly: 14, moves: ['d4c5','e7c5'], about: 'Take and attack!' } },
  { id: 'm-plan-benoni', title: 'Modern Benoni Structures', level: 'Advanced', hero: 'b',
    tagline: 'Pawn majority vs central squeeze.',
    desc: 'Black accepts a backward d-pawn for the ...b5 queenside majority and ...Ne5 outposts. White squeezes with e4-e5; Black rolls ...b4.',
    ideas: ['...b5! The majority must move.', '...Ne5 outpost is the compensation.', 'Never allow e4-e5 for free.'],
    line: ['d2d4','g8f6','c2c4','c7c5','d4d5','e7e6','b1c3','e6d5','c4d5','d7d6','e2e4'],
    notes: { 3: '2...c5! The Benoni challenge.' },
    drill: { afterPly: 9, moves: ['d7d6','e2e4'], about: 'Black to move: solidify!' } },
  { id: 'm-plan-benko', title: 'Benko Gambit Pressure', level: 'Advanced', hero: 'b',
    tagline: 'Sac a pawn for eternal files.',
    desc: 'The Benko gives b5 for the a/b-files and a monster g7-bishop. White nurses the pawn; Black attacks for 40 moves.',
    ideas: ['...b5! Open the files at once.', '...Ba6 trades White’s best piece.', '...e6-d5 breaks follow automatically.'],
    line: ['d2d4','g8f6','c2c4','c7c5','d4d5','b7b5','c4b5','a7a6','b5a6'],
    notes: { 5: '3...b5! The gambit begins.' },
    drill: { afterPly: 7, moves: ['a7a6','b5a6'], about: 'Black to move: undermine!' } },
  { id: 'm-plan-london-kid', title: 'London vs King’s Indian', level: 'Beginner', hero: 'w',
    tagline: 'Solid system, e5 break coming.',
    desc: 'London meets fianchetto: Bf4 outside the chain, e3-e4 coming, and Black’s ...e5 met by dxe5 pressure.',
    ideas: ['Bf4 first — never locked in.', 'e4! is the central goal.', 'Meet ...e5 with exchanges favoring you.'],
    line: ['d2d4','g8f6','c1f4','g7g6','e2e3','f8g7','g1f3','e8g8','f1e2','d7d6'],
    notes: { 2: '2.Bf4! The London signature.' },
    drill: { afterPly: 8, moves: ['f1e2','d7d6'], about: 'Solid development!' } },
  { id: 'm-plan-colle', title: 'Colle System Attack', level: 'Beginner', hero: 'w',
    tagline: 'd4-e3-Bd3 wall, then e4!',
    desc: 'The Colle: a stone wall center, Bxh7+ sacrifices brewing, and the e3-e4 break that opens everything.',
    ideas: ['Bd3 aims at h7 from move 4.', 'e4! is the break — prepare with Nbd2.', 'Bxh7+ sacrifices come free with the setup.'],
    line: ['d2d4','d7d5','g1f3','g8f6','e2e3','e7e6','f1d3','c7c5','c2c3','b8c6','b1d2'],
    notes: { 6: '4.Bd3! Eyes h7 already.' },
    drill: { afterPly: 8, moves: ['c2c3','b8c6','b1d2'], about: 'White to move: build e4!' } },
  { id: 'm-plan-torre', title: 'Torre Attack Plans', level: 'Beginner', hero: 'w',
    tagline: 'Bg5 before e3 locks the bishop.',
    desc: 'The Torre develops Bg5 before the e-pawn moves: pin pressure, quick e4 breaks, and ...c5 met by c3.',
    ideas: ['Bg5 early — never buried.', 'e4! follows in one move.', 'c3 answers ...c5 forever.'],
    line: ['d2d4','g8f6','g1f3','e7e6','c1g5','c7c5','e2e3','b7b6'],
    notes: { 4: '3.Bg5! Out before the chain.' },
    drill: { afterPly: 6, moves: ['e2e3','b7b6'], about: 'Support the center!' } },
  { id: 'm-plan-reti', title: 'Réti Opening Plans', level: 'Intermediate', hero: 'w',
    tagline: 'Flank pressure, strike the center late.',
    desc: 'The hypermodern Réti: Nf3-c4 first, let Black occupy, then undermine with b3-Bb2 and e3-d4 ideas.',
    ideas: ['Let Black build — then undermine.', 'Bb2 rakes the long diagonal.', 'd4! comes with full preparation.'],
    line: ['g1f3','d7d5','c2c4','d5c4','e2e3','g8f6','f1c4','e7e6'],
    notes: { 3: '2...dxc4?! Grabby — develop with gain.' },
    drill: { afterPly: 6, moves: ['f1c4','e7e6'], about: 'Regain with development!' } },
  { id: 'm-plan-kia', title: "King's Indian Attack", level: 'Beginner', hero: 'w',
    tagline: 'Same setup vs everything.',
    desc: 'The KIA plays itself: d3-e4-Nd2-Ngf3-g3-Bg2-O-O against anything Black tries, then e5 and kingside attack.',
    ideas: ['One setup vs all defenses.', 'e5! is the universal break.', 'Ne2-g3 reroutes never fail.'],
    line: ['e2e4','e7e6','d2d3','d7d5','b1d2','g8f6','g1f3','f8e7','g2g3','e8g8'],
    notes: { 8: '5.g3! The fianchetto completes the setup.' },
    drill: { afterPly: 8, moves: ['g2g3','e8g8'], about: 'White to move: setup complete!' } },
  { id: 'm-plan-grandprix', title: 'Grand Prix Attack', level: 'Intermediate', hero: 'w',
    tagline: 'f4 before Nf3: caveman chess that works.',
    desc: 'The Grand Prix skips Nf3 for f4: quick f5, Qe1-h4 swings, and 0-0-0 attacks that crush unprepared Sicilians.',
    ideas: ['f4 first — Nf3 can wait.', 'f5! opens lines with tempo.', 'Qe1-h4 swings decide games.'],
    line: ['e2e4','c7c5','b1c3','b8c6','f2f4','g7g6','g1f3','f8g7'],
    notes: { 4: '3.f4! The Grand Prix signature.' },
    drill: { afterPly: 6, moves: ['g1f3','f8g7'], about: 'Develop the attack!' } },
  { id: 'm-plan-alapin', title: 'Alapin: c3 Plans', level: 'Beginner', hero: 'w',
    tagline: 'No theory, just a strong center.',
    desc: 'The Alapin dodges all Sicilian theory: c3-d4 builds the perfect center, and isolated positions favor the better-developed side.',
    ideas: ['c3-d4: the full center, no tricks.', 'Isolated queen pawn? Attack with it.', 'Black’s ...e6 is passive — push d5.'],
    line: ['e2e4','c7c5','c2c3','d7d5','e4d5','d8d5','d2d4','g8f6','g1f3','e7e6'],
    notes: { 2: '2.c3! Sidesteps 20 moves of theory.' },
    drill: { afterPly: 8, moves: ['g1f3','e7e6'], about: 'Develop with tempo!' } },
  { id: 'm-plan-scandi', title: 'Scandinavian Structures', level: 'Beginner', hero: 'b',
    tagline: 'Queen out early, develop with gain.',
    desc: 'The Scandi gives ...Qxd5-a5: quick development, ...c6 support, and ...Bf5 before ...e6 — the bishop breathes.',
    ideas: ['...Qa5 keeps the queen active.', '...c6 supports ...d5 forever.', '...Bf5 before ...e6 — always.'],
    line: ['e2e4','d7d5','e4d5','d8d5','b1c3','d5a5','d2d4','g8f6','g1f3','c8f5','f1b5'],
    notes: { 5: '3...Qa5! Active and safe.' },
    drill: { afterPly: 9, moves: ['c8f5','f1b5'], about: 'Black to move: ...Bf5!' } },
  { id: 'm-plan-pirc', title: 'Pirc Defense Plans', level: 'Intermediate', hero: 'b',
    tagline: 'Let White build, then ...e5.',
    desc: 'The Pirc invites the center and strikes it: ...g6-Bg7 first, ...e5 or ...c5 breaks when White overextends.',
    ideas: ['Concede the center, then blast it.', '...e5! is the main break.', '...c5 works once d4 is weak.'],
    line: ['e2e4','d7d6','d2d4','g8f6','b1c3','g7g6','g1f3','f8g7','f1e2','e8g8','e1g1'],
    notes: { 5: '3...g6! Flexible fianchetto.' },
    drill: { afterPly: 9, moves: ['e8g8','e1g1'], about: 'Black to move: castle!' } },
  { id: 'm-plan-petrov', title: "Petroff Defense Plans", level: 'Intermediate', hero: 'b',
    tagline: 'Symmetry with a sting: ...d5.',
    desc: 'The Petroff mirrors and then breaks: ...Nxe4 ideas, ...d5 central strikes, and ...Nc6 development with tempo.',
    ideas: ['Mirror first, break with ...d5.', '...Nxe4 wins the center pawn.', 'Symmetry favors Black after exchanges.'],
    line: ['e2e4','e7e5','g1f3','g8f6','d2d4','f6e4','f1d3','d7d5','e1g1'],
    notes: { 5: '3...Nxe4! The whole point.' },
    drill: { afterPly: 7, moves: ['d7d5','e1g1'], about: 'Black to move: equalize!' } },
  { id: 'm-plan-vienna', title: 'Vienna Game Plans', level: 'Intermediate', hero: 'w',
    tagline: 'Nc3 first, f4 with tempo.',
    desc: 'The Vienna delays Nf3 to push f4 in one go: Black must react centrally (...d5!) or get rolled off the board.',
    ideas: ['Nc3 supports the f4 push.', 'f4-f5 rolls with gain.', '...d5! is Black’s only cure.'],
    line: ['e2e4','e7e5','b1c3','g8f6','f2f4','d7d5','f4e5','f6e4','f1c4'],
    notes: { 4: '3.f4! The Vienna gambit spirit.' },
    drill: { afterPly: 7, moves: ['f6e4','f1c4'], about: 'Black to move: centralize!' } },
  { id: 'm-plan-qga', title: "Queen's Gambit Accepted Plans", level: 'Intermediate', hero: 'b',
    tagline: 'Take, hold with ...c5, develop.',
    desc: 'The QGA concedes the center temporarily: ...c5 strikes back at once, and ...e6-Bxc5 develops with tempo on f2.',
    ideas: ['...c5! immediately — never passive.', '...e6 and ...Bxc5 with tempo.', '...Nc6 hits d4 forever.'],
    line: ['d2d4','d7d5','c2c4','d5c4','g1f3','g8f6','e2e3','e7e6','f1c4','c7c5','e3e4'],
    notes: { 9: '5...c5! The instant strike-back.' },
    drill: { afterPly: 9, moves: ['c7c5','e3e4'], about: 'Black to move: ...c5!' } },
  { id: 'm-plan-chigorin', title: 'Chigorin Defense Ideas', level: 'Advanced', hero: 'b',
    tagline: 'Knights before bishops, concretely.',
    desc: 'Chigorin’s provocation: ...Nc6 blocks the c-pawn but pressures d4 instantly, and ...Bxf3 damages White’s structure.',
    ideas: ['...Nc6 hits d4 on move 2.', '...Bxf3 doubles White’s pawns.', '...Qxd5 centralizes with gain.'],
    line: ['d2d4','d7d5','c2c4','b8c6','g1f3','c8g4','c4d5','g4f3','g2f3','d8d5','e2e3'],
    notes: { 3: '2...Nc6!? Provocation with a point.' },
    drill: { afterPly: 9, moves: ['d8d5','e2e3'], about: 'Black to move: centralize!' } },
  { id: 'm-plan-jobava', title: 'Jobava London System', level: 'Intermediate', hero: 'w',
    tagline: 'Nc3+Bf4: London with teeth.',
    desc: 'The Jobava adds Nc3 to the London: Qb3 pressure, Nb5 jumps, and e4 breaks with real attacking chances.',
    ideas: ['Nc3 first — Bf4 still comes.', 'Qb3 hits b7 before ...c6.', 'Nb5 jumps into every hole.'],
    line: ['d2d4','d7d5','b1c3','g8f6','c1f4','e7e6','e2e3','f8d6'],
    notes: { 2: '2.Nc3! The Jobava twist.' },
    drill: { afterPly: 6, moves: ['e2e3','f8d6'], about: 'Challenge the bishop!' } },
  { id: 'm-plan-french-advance', title: 'French Advance Plans', level: 'Intermediate', hero: 'w',
    tagline: 'e5 wedge, f4 break coming.',
    desc: 'The Advance French: e5 cramps Black, c3-d4 holds, and f4-f5 breaks through. Black undermines with ...c5 and ...Qb6.',
    ideas: ['e5 wedge takes f6 and d6.', 'f4-f5! is the thematic break.', 'Meet ...Qb6 with Qb3 tension.'],
    line: ['e2e4','e7e6','d2d4','d7d5','e4e5','c7c5','c2c3','b8c6','g1f3','f8e7'],
    notes: { 4: '3.e5! Space with tempo.' },
    drill: { afterPly: 8, moves: ['g1f3','f8e7'], about: 'White to move: develop!' } },
  { id: 'm-plan-french-exchange', title: 'French Exchange Symmetry', level: 'Beginner', hero: 'w',
    tagline: 'Symmetry — then outplay them.',
    desc: 'The Exchange French looks drawish, but Bd3-c2-Qe2 plans and minority ideas give White all the fun.',
    ideas: ['Symmetry means no losing.', 'Bd3-Qe2 eyes h7.', 'c4! breaks symmetry favorably.'],
    line: ['e2e4','e7e6','d2d4','d7d5','e4d5','e6d5','g1f3','g8f6','f1d3','f8d6'],
    notes: { 8: '5.Bd3! Eyes h7 already.' },
    drill: { afterPly: 8, moves: ['f1d3','f8d6'], about: 'Mirror and improve!' } },
  { id: 'm-plan-caro-advance', title: 'Caro Advance Plans', level: 'Intermediate', hero: 'w',
    tagline: 'e5 wedge vs the strong bishop.',
    desc: 'The Advance Caro: e5 cramps, but Black’s bishop escapes via f5. f4-g4 hunting plans punish it.',
    ideas: ['e5 wedge first, questions later.', 'Hunt ...Bf5 with f4-g4 ideas.', 'Short castle keeps f-pawns mobile.'],
    line: ['e2e4','c7c6','d2d4','d7d5','e4e5','c8f5','g1f3','e7e6','f1e2','g8f6'],
    notes: { 4: '3.e5! Cramping at once.' },
    drill: { afterPly: 8, moves: ['f1e2','g8f6'], about: 'White to move: keep it solid!' } },
  { id: 'm-plan-caro-exchange', title: 'Caro Exchange: Panov Lite', level: 'Beginner', hero: 'w',
    tagline: 'Open lines, quick development.',
    desc: 'The Exchange Caro opens the game early: Bb5+ ideas, fast castling, and central pressure with no theory burden.',
    ideas: ['Exchanges free your pieces.', 'Bb5+ develops with tempo.', 'd4-c4 plans build the center.'],
    line: ['e2e4','c7c6','d2d4','d7d5','e4d5','c6d5','g1f3','b8c6','f1b5','e7e6'],
    notes: { 8: '5.Bb5+! Tempo development.' },
    drill: { afterPly: 8, moves: ['f1b5','e7e6'], about: 'White to move: check!' } },
  { id: 'm-plan-alekhine', title: "Alekhine's Defense Provocation", level: 'Intermediate', hero: 'b',
    tagline: 'Lure pawns, strike them.',
    desc: 'The Alekhine lures White forward with ...Nf6, then undermines the overextended center with ...d6 and ...c5.',
    ideas: ['Provoke e5, then hit it.', '...d6 undermines at once.', '...c5 follows when d4 is weak.'],
    line: ['e2e4','g8f6','e4e5','f6d5','d2d4','d7d6','c2c4','d5b6','b1c3'],
    notes: { 1: '1...Nf6! The provocation begins.' },
    drill: { afterPly: 7, moves: ['d5b6','b1c3'], about: 'Black to move: retreat!' } },
  { id: 'm-plan-modern', title: 'Modern Defense Fianchetto', level: 'Intermediate', hero: 'b',
    tagline: 'Hypermodern: ...g6 first.',
    desc: 'The Modern lets White build, then strikes with ...e5 or ...c5. The g7-bishop rakes the center White overextended into.',
    ideas: ['...g6-Bg7 before committing.', '...e5! is the main counter.', 'White’s center is a target, not a trophy.'],
    line: ['e2e4','g7g6','d2d4','f8g7','b1c3','d7d6','g1f3','e7e5','d4e5'],
    notes: { 7: '4...e5! Strike the center.' },
    drill: { afterPly: 7, moves: ['e7e5','d4e5'], about: 'Black to move: ...e5!' } },
  { id: 'm-plan-petrov-classical', title: 'Petroff Classical Center', level: 'Intermediate', hero: 'b',
    tagline: 'Mirror, take, strike ...d5.',
    desc: 'The classical Petroff: ...Nxe4 centralizes, ...d5 equalizes by force, and symmetry favors Black’s development.',
    ideas: ['...Nxe4 first — free center pawn.', '...d5 equalizes immediately.', 'Develop with tempo on d4.'],
    line: ['e2e4','e7e5','g1f3','g8f6','d2d4','f6e4','f1d3','d7d5','e1g1'],
    notes: { 5: '3...Nxe4! The whole point.' },
    drill: { afterPly: 7, moves: ['d7d5','e1g1'], about: 'Black to move: strike!' } },
  { id: 'm-plan-philidor', title: "Philidor Defense Solidity", level: 'Beginner', hero: 'b',
    tagline: '...d6 holds everything.',
    desc: 'The Philidor is humble and hard to crack: ...d6 supports e5, ...Nbd7 develops inside, and ...Be7 castles into safety.',
    ideas: ['...d6 defends e5 forever.', '...Nbd7 keeps the center fluid.', '...exd4 opens your game when ready.'],
    line: ['e2e4','e7e5','g1f3','d7d6','d2d4','g8f6','b1c3','b8d7'],
    notes: { 3: '2...d6! Humble and solid.' },
    drill: { afterPly: 6, moves: ['b1c3','b8d7'], about: 'Reroute inside!' } },
  { id: 'm-plan-ponziani', title: 'Ponziani Surprise Value', level: 'Intermediate', hero: 'w',
    tagline: '3.c3 with ...d5 tricks.',
    desc: 'The forgotten Ponziani: c3-d4 builds big, Qa4 hits in many lines, and booked opponents burn time early.',
    ideas: ['c3-d4: the full center.', 'Qa4 exploits ...d5 looseness.', 'Surprise value is real compensation.'],
    line: ['e2e4','e7e5','g1f3','b8c6','c2c3','d7d5','d1a4','c8d7'],
    notes: { 6: '4.Qa4! Concrete problems already.' },
    drill: { afterPly: 6, moves: ['d1a4','c8d7'], about: 'White to move: Qa4!' } },
  { id: 'm-plan-scotch', title: 'Scotch Game Open Play', level: 'Intermediate', hero: 'w',
    tagline: 'd4 at once, open everything.',
    desc: 'The Scotch skips theory for open piece play: d4, exchanges, and fast development favor the better tactician.',
    ideas: ['d4 opens before Black settles.', 'Nxd4 recaptures toward activity.', '...Nf6 is met by Nxc6 damage.'],
    line: ['e2e4','e7e5','g1f3','b8c6','d2d4','e5d4','f3d4','g8f6'],
    notes: { 4: '3.d4! Open games for open minds.' },
    drill: { afterPly: 6, moves: ['f3d4','g8f6'], about: 'Recapture actively!' } },
  { id: 'm-plan-ruy-exchange', title: 'Ruy Exchange Grind', level: 'Intermediate', hero: 'w',
    tagline: 'Damage the structure, grind.',
    desc: 'Fischer’s Exchange: Bxc6 doubles pawns, White heads for a better endgame with 0-0 and f4 breaks.',
    ideas: ['Bxc6 doubles and isolates.', 'Endgames are White’s kingdom.', 'f4! breaks at the right moment.'],
    line: ['e2e4','e7e5','g1f3','b8c6','f1b5','a7a6','b5c6','d7c6'],
    notes: { 6: '4.Bxc6! Structure first, mate later.' },
    drill: { afterPly: 6, moves: ['b5c6','d7c6'], about: 'Inflict the doubles!' } },
  { id: 'm-plan-ruy-berlin', title: 'Berlin Wall Plans (Black)', level: 'Advanced', hero: 'b',
    tagline: 'Trade queens, hold the endgame.',
    desc: 'Kramnik’s Wall: 3...Nf6 invites the endgame where Black’s bishop pair and structure hold everything.',
    ideas: ['...Nf6 invites the endgame.', 'Bishops + structure = draw with teeth.', '...Ne4 centralizes with tempo.'],
    line: ['e2e4','e7e5','g1f3','b8c6','f1b5','g8f6','e1g1'],
    notes: { 5: '3...Nf6! The Wall goes up.' },
    drill: { afterPly: 5, moves: ['g8f6','e1g1'], about: 'Black to move: ...Nf6!' } },
  { id: 'm-plan-qgd-orthodox', title: 'QGD Orthodox Plans', level: 'Intermediate', hero: 'b',
    tagline: 'Classical development, ...0-0.',
    desc: 'The Orthodox is chess’s backbone: ...Be7, ...O-O, ...Nbd7 — solid, flexible, and ready for ...c5 or ...e5.',
    ideas: ['...Be7 before ...O-O, always.', '...Nbd7 supports ...c5.', '...c5! is the freeing break.'],
    line: ['d2d4','d7d5','c2c4','e7e6','b1c3','g8f6','c1g5','f8e7','e2e3'],
    notes: { 7: '4...Be7! Classical and calm.' },
    drill: { afterPly: 7, moves: ['f8e7','e2e3'], about: 'Black to move: ...Be7!' } },
  { id: 'm-plan-qgd-exchange', title: 'QGD Exchange: Minority Lives', level: 'Intermediate', hero: 'w',
    tagline: 'Carlsbad structure, b4-b5 coming.',
    desc: 'The Exchange Carlsbad: fixed pawns, then Rb1 and b4-b5 minority breaks. See the full course in Strategy middlegame.',
    ideas: ['cxd5 fixes the structure.', 'Rb1-b4-b5 is the plan.', 'Black’s ...c5 must be stopped.'],
    line: ['d2d4','d7d5','c2c4','e7e6','c4d5','e6d5','b1c3','g8f6'],
    notes: { 4: '3.cxd5! Structure fixed.' },
    drill: { afterPly: 6, moves: ['b1c3','g8f6'], about: 'Develop the Carlsbad!' } },
  { id: 'm-plan-slav-exchange', title: 'Slav Exchange Symmetry', level: 'Beginner', hero: 'w',
    tagline: 'Symmetry with the move.',
    desc: 'The Slav Exchange: symmetrical but White moves first — Bf4, e3, Bd3 plans keep a pull forever.',
    ideas: ['Symmetry + move = lasting pull.', 'Bf4 develops outside.', 'c5! breaks when ready.'],
    line: ['d2d4','d7d5','c2c4','c7c6','c4d5','c6d5','b1c3','g8f6'],
    notes: { 4: '3.cxd5! Simple and good.' },
    drill: { afterPly: 6, moves: ['b1c3','g8f6'], about: 'Natural development!' } },
  { id: 'm-plan-bird', title: "Bird's Opening Attack", level: 'Beginner', hero: 'w',
    tagline: 'f4 with Dutch reversed.',
    desc: 'The Bird plays the Dutch a tempo up: f4-e3, Nf3, Be2, 0-0 — then e4 or g4 storms depending on Black’s setup.',
    ideas: ['f4 first — systemeredge.', 'e3-Be2-0-0: safe king.', 'e4! or g4! chooses the war.'],
    line: ['f2f4','d7d5','g1f3','g8f6','e2e3','e7e6','b2b3','f8e7','c1b2'],
    notes: { 0: '1.f4! The Bird flies at once.' },
    drill: { afterPly: 6, moves: ['b2b3','f8e7','c1b2'], about: 'White to move: fianchetto!' } },
  { id: 'm-plan-closed-sicilian', title: 'Closed Sicilian Kingside', level: 'Intermediate', hero: 'w',
    tagline: 'Slow build, f4-f5 storm.',
    desc: 'The Closed avoids theory: Nc3-g3-Bg2 setup, then f4-f5 opens Black’s king with Qe1-h4 swings.',
    ideas: ['No d4 — slow squeeze instead.', 'f4-f5! is the whole plan.', 'Qe1-h4 swings decide.'],
    line: ['e2e4','c7c5','b1c3','b8c6','g2g3','g7g6','f1g2','f8g7'],
    notes: { 4: '3.g3! The closed setup begins.' },
    drill: { afterPly: 6, moves: ['f1g2','f8g7'], about: 'Double fianchetto!' } },
  { id: 'm-plan-dragon', title: 'Dragon: Yugoslav Plans', level: 'Advanced', hero: 'w',
    tagline: 'Be3-f3-Qd2 vs ...g6.',
    desc: 'Anti-Dragon 101: Be3-Qd2-0-0-0 setup meets ...g6, then h4-h5 storms before Black’s ...d5 frees the game.',
    ideas: ['Be3-Qd2-0-0-0: the machine.', 'h4-h5! opens lines fast.', '...d5 must be stopped by e4-e5.'],
    line: ['e2e4','c7c5','g1f3','d7d6','d2d4','c5d4','f3d4','g8f6','b1c3','g7g6','f1e2'],
    notes: { 9: '5...g6! The Dragon breathes.' },
    drill: { afterPly: 9, moves: ['g7g6','f1e2'], about: 'Black to move: ...g6!' } },
];
