// 17 motif lessons: 5 pins + 5 skewers + 4 forks + 3 discovered/double-checks.
export const MOTIFS = [
  { id: 'm-pin-spanish', title: 'Pin: Spanish Bishop', level: 'Beginner', hero: 'w',
    tagline: 'Bb5 pins the defender of e5.',
    desc: 'The Ruy Lopez pin: Bb5 nails the c6-knight to duties. Black’s center becomes brittle because the defender cannot move.',
    ideas: ['Bb5 pins the e5-defender at once.', '...a6 questions it — keep tension with Ba4.', 'Pile on e5 while it is pinned.'],
    line: ['e2e4','e7e5','g1f3','b8c6','f1b5','a7a6','b5a4','g8f6'],
    notes: { 4: '3.Bb5! The pin defines the Ruy Lopez.' },
    drill: { afterPly: 6, moves: ['b5a4','g8f6'], about: 'White to play: keep the pin!' } },
  { id: 'm-pin-italian-bg4', title: 'Pin: ...Bg4 on f3', level: 'Intermediate', hero: 'b',
    tagline: 'Pin the knight, pressure d4.',
    desc: 'Black’s ...Bg4 pins Nf3 to the white queen. White must break it with h3 or live with doubled f-pawns.',
    ideas: ['...Bg4 pins before White settles.', 'h3/Bh4 loosens but concedes tempo.', '...Bxf3 doubles pawns when good.'],
    line: ['e2e4','e7e5','g1f3','b8c6','f1c4','f8c5','c2c3','g8f6','d2d3','d7d6','c1g5'],
    notes: { 10: '6.Bg5! White pins back — pin warfare.' },
    drill: { afterPly: 9, moves: ['d7d6','c1g5'], about: 'Solidify, then face the pin!' } },
  { id: 'm-pin-qgd', title: 'Pin: QGD ...Bg5', level: 'Beginner', hero: 'w',
    tagline: 'Bg5 pins the f6-knight.',
    desc: 'The Queen’s Gambit pin: Bg5 nails Nf6 to the queen. Black must unpin with ...Be7 before castling.',
    ideas: ['Bg5 develops with a threat.', '...Be7 is the honest unpin.', 'Bxf6 doubles pawns in many lines.'],
    line: ['d2d4','d7d5','c2c4','e7e6','b1c3','g8f6','c1g5','b8d7'],
    notes: { 6: '4.Bg5! The pin comes with development.' },
    drill: { afterPly: 6, moves: ['c1g5','b8d7'], about: 'White to play: pin!' } },
  { id: 'm-pin-nimzo', title: 'Pin: Nimzo-Indian ...Bb4', level: 'Intermediate', hero: 'b',
    tagline: 'Pin and double the c-pawns.',
    desc: 'The Nimzo pin: ...Bb4 nails Nc3, then ...Bxc3 doubles White’s pawns and hands Black the bishop pair.',
    ideas: ['...Bb4 pins before White plays e3.', '...Bxc3 doubles pawns with interest.', 'The bishop pair rules the sequel.'],
    line: ['d2d4','g8f6','c2c4','e7e6','b1c3','f8b4','e2e3'],
    notes: { 5: '3...Bb4! The Nimzo signature pin.' },
    drill: { afterPly: 5, moves: ['f8b4','e2e3'], about: 'Black to move: the pin!' } },
  { id: 'm-pin-break-h6', title: 'Breaking Pins with ...h6', level: 'Beginner', hero: 'b',
    tagline: 'Ask the bishop: ...h6.',
    desc: 'The universal unpin: ...h6 kicks the bishop before castling into trouble. Bh4 keeps tension; Bxf6 accepts the structure.',
    ideas: ['...h6 before ...O-O in pin lines.', 'Bh4 retreats keep the pin alive.', 'Never allow Ng5 with mate ideas.'],
    line: ['d2d4','d7d5','c2c4','e7e6','b1c3','g8f6','c1g5','f8e7','e2e3','e8g8','g1f3','h7h6','g5h4'],
    notes: { 11: '6...h6! The question every pin must answer.' },
    drill: { afterPly: 11, moves: ['h7h6','g5h4'], about: 'Black to move: ask the bishop!' } },
  { id: 'm-skewer-rook-rank', title: 'Skewer: Check the Rank, Take the File', level: 'Intermediate', hero: 'w',
    tagline: 'Rh4+ pulls the king off guard.',
    desc: 'The rank-to-file skewer: Rh4+ checks along the rank, the king abandons the h-file, and Rxh8 collects the rook.',
    ideas: ['Check along one line, capture along another.', 'The king cannot stay to shield.', 'Rxh8 finishes — count the flight squares.'],
    startFen: '7r/8/8/7k/8/8/5PP1/6KR w - - 0 1',
    line: ['h1h4','h5g6','h4h8'],
    notes: { 0: '1.Rh4+! The king must abandon the file.', 2: '2.Rxh8! The skewer collects.' },
    drill: { startFen: '7r/8/8/7k/8/8/5PP1/6KR w - - 0 1', moves: ['h1h4','h5g6'], about: 'White to play: skewer!' } },
  { id: 'm-skewer-rook-a', title: 'Skewer: Rook Up the File', level: 'Beginner', hero: 'w',
    tagline: 'Ra5+ pulls the king off guard.',
    desc: 'The file skewer: Ra5+ checks the shielding king along the rank, Kb6 steps off the file, and Rxa8 collects the rook.',
    ideas: ['Check from the side when the file is blocked.', 'The king must abandon its shield.', 'Rxa8 finishes — always verify the flight.'],
    startFen: 'r7/8/k7/8/8/8/5PPP/R5K1 w - - 0 1',
    line: ['a1a5','a6b6','a5a8'],
    notes: { 0: '1.Ra5+! Check — the king shield must move.', 2: '2.Rxa8! The skewer collects.' },
    drill: { startFen: 'r7/8/k7/8/8/8/5PPP/R5K1 w - - 0 1', moves: ['a1a5','a6b6'], about: 'White to play: skewer up the file!' } },
  { id: 'm-skewer-rook-h', title: 'Skewer: Rook Up the h-File', level: 'Beginner', hero: 'w',
    tagline: 'Rh7+! Same pattern, other wing.',
    desc: 'Mirror of the a-file skewer: Rh7+ checks the shielding king, Kg6 steps, Rook takes. Patterns repeat — learn both wings.',
    ideas: ['Same shape as the a-file skewer.', '1...Kg6 is the only sidestep.', '2.Rxh8 wins the exchange.'],
    startFen: '7r/8/7k/8/8/8/5PP1/6KR w - - 0 1',
    line: ['h1h5','h6g6','h5h8'],
    notes: { 0: '1.Rh5+! Check — the king shield must move.', 2: '2.Rxh8! Pattern complete.' },
    drill: { startFen: '7r/8/7k/8/8/8/5PP1/6KR w - - 0 1', moves: ['h1h5','h6g6'], about: 'White to play: skewer!' } },
  { id: 'm-skewer-bishop-check', title: 'Skewer: Check First, Take Second', level: 'Intermediate', hero: 'w',
    tagline: 'Bf3+ moves the king, wins the queen.',
    desc: 'The checking skewer: Bf3+ forces the king off the queen’s guard, then Bxd5 collects. Checks make skewers forcing.',
    ideas: ['Give check along the skewer line.', 'The king must abandon its guard.', 'Take the bigger piece second.'],
    startFen: '8/8/8/3q4/4k3/8/5PBP/6K1 w - - 0 1',
    line: ['g2f3','e4d4','f3d5'],
    notes: { 0: '1.Bf3+! Check — the king must move.', 2: '2.Bxd5! The queen falls.' },
    drill: { startFen: '8/8/8/3q4/4k3/8/5PBP/6K1 w - - 0 1', moves: ['g2f3','e4d4'], about: 'White to play: check-skewer!' } },
  { id: 'm-skewer-bishop-check-2', title: 'Skewer: Long Diagonal Check', level: 'Intermediate', hero: 'w',
    tagline: 'Bf2+ moves the king, wins the queen.',
    desc: 'Same forcing shape up the long diagonal: Bf2+ checks, the king abandons its guard, Bxb6 collects. Drill both until automatic.',
    ideas: ['Checks force the king off guard.', 'Take the loose piece second.', 'Skewer lines repeat across games.'],
    startFen: '8/8/1q6/8/3k4/8/6PP/6BK w - - 0 1',
    line: ['g1f2','d4e5','f2b6'],
    notes: { 0: '1.Bf2+! Same forcing idea.', 2: '2.Bxb6! Collected.' },
    drill: { startFen: '8/8/1q6/8/3k4/8/6PP/6BK w - - 0 1', moves: ['g1f2','d4e5'], about: 'White to play: check-skewer!' } },
  { id: 'm-fork-knight-kq', title: 'Fork: Knight Takes Queen', level: 'Beginner', hero: 'w',
    tagline: 'Ne7+ forks king and queen.',
    desc: 'The royal fork: Ne7+ checks the king on g8 while hitting the queen on c8. One move wins the queen.',
    ideas: ['Ne7+ hits g8 and c8 together.', 'Kh8 is forced — then Nxc8.', 'Knights on e7/d7 are monster outposts.'],
    startFen: '2q3k1/8/8/3N4/8/8/5PPP/6K1 w - - 0 1',
    line: ['d5e7','g8h8','e7c8'],
    notes: { 0: '1.Ne7+! Royal fork — check plus queen.', 2: '2.Nxc8! The queen falls.' },
    drill: { startFen: '2q3k1/8/8/3N4/8/8/5PPP/6K1 w - - 0 1', moves: ['d5e7','g8h8'], about: 'White to play: fork!' } },
  { id: 'm-fork-knight-kr', title: 'Fork: Knight Takes Rook', level: 'Beginner', hero: 'w',
    tagline: 'Nd6+ forks king and rook.',
    desc: 'Same royal idea vs a rook: Nd6+ checks on e8 and hits f7. Kd8 steps, Nxf7 collects.',
    ideas: ['Nd6+ hits e8 and f7 together.', 'Kd8 is forced off the file.', '2.Nxf7 wins the exchange.'],
    startFen: '4k3/5r2/8/5N2/8/8/5PPP/6K1 w - - 0 1',
    line: ['f5d6','e8d8','d6f7'],
    notes: { 0: '1.Nd6+! Fork with check.', 2: '2.Nxf7! The rook falls.' },
    drill: { startFen: '4k3/5r2/8/5N2/8/8/5PPP/6K1 w - - 0 1', moves: ['f5d6','e8d8'], about: 'White to play: fork!' } },
  { id: 'm-fork-pawn', title: 'Fork: Pawn Takes Bishop', level: 'Beginner', hero: 'w',
    tagline: 'd5 attacks knight and bishop.',
    desc: 'Pawns fork too: d5 hits the knight and bishop together. The knight flees, the bishop falls.',
    ideas: ['d5! attacks two pieces at once.', 'The knight must move — tempo gained.', 'dxe6 collects the bishop.'],
    startFen: '6k1/8/2n1b3/8/3P4/8/5PPP/6K1 w - - 0 1',
    line: ['d4d5','c6e5','d5e6'],
    notes: { 0: '1.d5! Pawn fork — knight and bishop hang.', 2: '2.dxe6! The bishop falls.' },
    drill: { startFen: '6k1/8/2n1b3/8/3P4/8/5PPP/6K1 w - - 0 1', moves: ['d4d5','c6e5'], about: 'White to play: pawn fork!' } },
  { id: 'm-fork-knight-corner', title: 'Fork: Cornered King Falls', level: 'Intermediate', hero: 'w',
    tagline: 'Nc7+ forks king and rook.',
    desc: 'Corner kings invite forks: Nc7+ checks on a8 and hits e8. Kb8 steps, Nxe8 wins the rook.',
    ideas: ['Cornered kings + knights = danger.', 'Nc7+ checks and forks together.', 'Count the fork squares before sacrificing.'],
    startFen: 'k3r3/8/8/1N6/8/8/5PPP/6K1 w - - 0 1',
    line: ['b5c7','a8b8','c7e8'],
    notes: { 0: '1.Nc7+! Check plus rook.', 2: '2.Nxe8! The rook falls.' },
    drill: { startFen: 'k3r3/8/8/1N6/8/8/5PPP/6K1 w - - 0 1', moves: ['b5c7','a8b8'], about: 'White to play: fork!' } },
  { id: 'm-discovered-bishop', title: 'Discovered Check Wins Tempo', level: 'Intermediate', hero: 'w',
    tagline: 'Nf6+ unmasks the bishop.',
    desc: 'The knight steps with check from the bishop behind: Nf6+ discovers Bg2’s check and gains a free improving move.',
    ideas: ['Move the mask with check.', 'Discovered checks force replies.', 'Use the tempo to centralize.'],
    startFen: '8/8/8/3k4/4N3/8/5PBP/6K1 w - - 0 1',
    line: ['e4f6','d5e6','f6d5'],
    notes: { 0: '1.Nf6+! Discovered check — free tempo.' },
    drill: { startFen: '8/8/8/3k4/4N3/8/5PBP/6K1 w - - 0 1', moves: ['e4f6','d5e6'], about: 'White to play: discover check!' } },
  { id: 'm-double-check-edge', title: 'Double Check on the Edge', level: 'Intermediate', hero: 'w',
    tagline: 'Nh6+ checks twice at once.',
    desc: 'Double check is forcing: Nh6+ attacks with knight and bishop together. Only a king move answers — Kh8 walks in, Nxf7 follows.',
    ideas: ['Double checks allow only king moves.', 'Kh8 is forced to the corner.', 'Nxf7+ keeps the initiative.'],
    startFen: '6k1/8/8/5N2/2B5/8/5PPP/6K1 w - - 0 1',
    line: ['f5h6','g8h8','h6f7'],
    notes: { 0: '1.Nh6+! Double check — king must walk.' },
    drill: { startFen: '6k1/8/8/5N2/2B5/8/5PPP/6K1 w - - 0 1', moves: ['f5h6','g8h8'], about: 'White to play: double check!' } },
  { id: 'm-double-check-center', title: 'Double Check in the Center', level: 'Intermediate', hero: 'w',
    tagline: 'Nf6+ unmasks the rook too.',
    desc: 'Knight plus rook combine: Nf6+ checks with both pieces. Kd8 flees, Nd5 centralizes with a winning position.',
    ideas: ['Two checkers — king must run.', 'Kd8 abandons the center.', 'Nd5 dominates for free.'],
    startFen: '4k3/8/8/8/4N3/8/5PPP/R5K1 w - - 0 1',
    line: ['e4f6','e8d8','f6d5'],
    notes: { 0: '1.Nf6+! Double check — Kd8 forced.' },
    drill: { startFen: '4k3/8/8/8/4N3/8/5PPP/R5K1 w - - 0 1', moves: ['e4f6','e8d8'], about: 'White to play: double check!' } },
];
