// 18 famous trap/miniature lessons (all lines from the start position).
export const TRAPS = [
  { id: 'm-trap-legal', title: 'Legal Trap', level: 'Beginner', hero: 'w',
    tagline: 'Sac the queen, mate with two knights.',
    desc: 'The most famous trap ever: Black grabs the queen on d1 and gets mated by two minor pieces. Legal’s 1750 gem teachesNd5# patterns and why ...Bxd1?? loses.',
    ideas: ['6.Nxe5! offers the queen — Black cannot resist.', 'Bxf7+ drags the king out with check.', 'Nd5# is a pure smothered mate.'],
    line: ['e2e4','e7e5','g1f3','b8c6','f1c4','d7d6','b1c3','c8g4','h2h3','g4h5','f3e5','h5d1','c4f7','e8e7','c3d5'],
    notes: { 10: '6.Nxe5! The trap is set — the queen is poisoned.', 12: '7.Bxf7+! Check first, questions later.', 14: '8.Nd5# MATE — the queen was a decoy!' },
    drill: { afterPly: 10, moves: ['f3e5','h5d1','c4f7'], about: 'White to play: spring the Legal Trap!' } },
  { id: 'm-trap-blackburne', title: 'Blackburne Shilling Trap', level: 'Beginner', hero: 'b',
    tagline: 'Punish 4.Nxe5 with ...Qg5 and mate.',
    desc: 'Blackburne’s pub trick against the Italian: greedy Nxe5 meets ...Qg5, the knight falls with check, and a smothered mate follows on f3.',
    ideas: ['4...Qg5! hits g2 and the e5-knight at once.', '5...Qxg2 wins a rook while keeping the attack.', '7...Nf3# ends it — know the pattern to avoid it.'],
    line: ['e2e4','e7e5','g1f3','b8c6','f1c4','c6d4','f3e5','d8g5','e5f7','g5g2','h1f1','g2e4','c4e2','d4f3'],
    notes: { 7: '4...Qg5! Double attack — the trap begins.', 13: '7...Nf3# MATE. Never play 4.Nxe5 here.' },
    drill: { afterPly: 9, moves: ['g5g2','h1f1'], about: 'Black to move: win the rook!' } },
  { id: 'm-trap-fried-liver', title: 'Fried Liver Attack', level: 'Intermediate', hero: 'w',
    tagline: 'Sac the knight on f7 and cook the king.',
    desc: 'The most feared club weapon: 6.Nxf7! destroys Black’s kingside and drags the king into a hurricane. Even optimal defense leaves White better.',
    ideas: ['6.Nxf7! works because Qf3+ follows with tempo.', 'Black’s king can never castle again.', '5...Na5 (instead of Nxd5) is the only sane reply.'],
    line: ['e2e4','e7e5','g1f3','b8c6','f1c4','g8f6','f3g5','d7d5','e4d5','f6d5','g5f7','e8f7','d1f3'],
    notes: { 10: '6.Nxf7! The liver is served — Kxf7 is forced.', 12: '7.Qf3+! Check first; Black’s king is homeless.' },
    drill: { afterPly: 8, moves: ['e4d5','f6d5','g5f7'], about: 'White to play: start the Fried Liver!' } },
  { id: 'm-trap-noah', title: "Noah's Ark Trap", level: 'Intermediate', hero: 'b',
    tagline: 'Trap the queen with ...c5 and ...c4.',
    desc: 'White’s queen goes pawn-grabbing in the Ruy Lopez and Black closes the ark: ...c5 gains time, ...Be6 hits the queen, ...c4 traps the bishop.',
    ideas: ['8.Qxd4?? is greed — develop instead.', '9...Be6! attacks the queen with tempo.', '11...c4! The bishop has no escape.'],
    line: ['e2e4','e7e5','g1f3','b8c6','f1b5','a7a6','b5a4','d7d6','d2d4','b7b5','a4b3','c6d4','f3d4','e5d4','d1d4','c7c5','d4d5','c8e6','d5c6','e6d7','c6d5','c5c4'],
    notes: { 15: '8.Qxd4?? Greed! Black now hunts the queen.', 21: '11...c4! The ark closes — bishop trapped.' },
    drill: { afterPly: 15, moves: ['c7c5','d4d5'], about: 'Black to move: hunt the queen!' } },
  { id: 'm-trap-elephant', title: 'Elephant Trap', level: 'Intermediate', hero: 'b',
    tagline: 'Punish 6.Nxd5 with a queen trap.',
    desc: 'In the Queen’s Gambit, 6.Nxd5?? looks free but 6...Nxd5! 7.Bxd8 Bb4+ wins the queen back with check — a whole queen swing for nothing.',
    ideas: ['6.Nxd5?? ignores ...Bb4+.', '7...Bb4+! Check first — White must block.', '8...Bxd2+ wins the queen back.'],
    line: ['d2d4','d7d5','c2c4','e7e6','b1c3','g8f6','c1g5','b8d7','c4d5','e6d5','c3d5','f6d5','g5d8','f8b4','d1d2','b4d2','e1d2','e8d8'],
    notes: { 11: '6...Nxd5! Calmly recaptures — the trap is ready.', 13: '7...Bb4+! The elephant steps in with check.' },
    drill: { afterPly: 11, moves: ['f6d5','g5d8'], about: 'Black to move: set the trap!' } },
  { id: 'm-trap-stafford', title: 'Stafford Gambit Mate', level: 'Intermediate', hero: 'b',
    tagline: 'Sac the queen, deliver ...Bg4 mate.',
    desc: 'The internet’s favorite gambit ends in a forced mate: 6.Bg5? Nxe4! removes the defender, the queen falls, and ...Bg4 is mate.',
    ideas: ['6...Nxe4! destroys the f2 defender’s guard.', '7...Bxf2+ drags the king out.', '8...Bg4# is mate — memorize the finale.'],
    line: ['e2e4','e7e5','g1f3','g8f6','f3e5','b8c6','e5c6','d7c6','d2d3','f8c5','c1g5','f6e4','g5d8','c5f2','e1e2','c8g4'],
    notes: { 11: '6...Nxe4! Thematic — f2 is suddenly weak.', 15: '8...Bg4# MATE. Never play 6.Bg5 here.' },
    drill: { afterPly: 13, moves: ['c5f2','e1e2'], about: 'Black to move: drag the king out!' } },
  { id: 'm-trap-cambridge', title: 'Cambridge Springs Trap', level: 'Advanced', hero: 'b',
    tagline: 'Punish 9.Bd3 with ...dxc4.',
    desc: 'A deep Queen’s Gambit trap: 9.Bd3?? walks into ...dxc4!, when White drops a piece to ...Bxc3 tactics.',
    ideas: ['8...O-O lulls White into natural moves.', '9.Bd3?? drops material to ...dxc4.', '...Bxc3 finishes — always count the captures.'],
    line: ['d2d4','d7d5','c2c4','e7e6','b1c3','g8f6','c1g5','b8d7','e2e3','c7c6','g1f3','d8a5','f3d2','f8b4','d1c2','e8g8','f1d3','d5c4','d3c4','b4c3'],
    notes: { 17: '9...dxc4! The point — White drops a piece.', 19: '10...Bxc3! The point lands.' },
    drill: { afterPly: 17, moves: ['d5c4','d3c4','b4c3'], about: 'Black to play: spring ...dxc4!' } },
  { id: 'm-trap-scotch-qe7', title: 'Scotch: ...Qe7 Pin', level: 'Intermediate', hero: 'b',
    tagline: 'Pin the e-pawn and win it back.',
    desc: 'After 6.e5, Black doesn’t retreat — 6...Qe7! pins the pawn to the white queen and wins it back with interest.',
    ideas: ['6...Qe7! The pin wins the pawn back.', '7...Nd5 blocks and develops.', 'White’s center evaporates — Black stands better.'],
    line: ['e2e4','e7e5','g1f3','b8c6','d2d4','e5d4','f3d4','g8f6','d4c6','b7c6','e4e5','d8e7','d1e2','f6d5'],
    notes: { 11: '6...Qe7! The pin — e5 cannot be held.', 13: '7...Nd5! Blocks, develops, wins.' },
    drill: { afterPly: 11, moves: ['d8e7','d1e2'], about: 'Black to move: pin with ...Qe7!' } },
  { id: 'm-trap-4nxe5', title: 'Four Knights: 4.Nxe5 Refuted', level: 'Beginner', hero: 'b',
    tagline: 'Meet the pawn grab with ...Nxe5.',
    desc: '4.Nxe5?! looks free but 4...Nxe5! 5.d4 Bd6! returns the favor — Black regains the pawn with the better center.',
    ideas: ['4...Nxe5! Centralize with tempo.', '5...Bd6! develops while hitting h2.', 'Never grab e5 without the d4 follow-up ready.'],
    line: ['e2e4','e7e5','g1f3','b8c6','b1c3','g8f6','f3e5','c6e5','d2d4','f8d6'],
    notes: { 7: '4...Nxe5! The refutation — d4 comes with tempo.' },
    drill: { afterPly: 7, moves: ['c6e5','d2d4','f8d6'], about: 'Black to move: centralize!' } },
  { id: 'm-trap-petroff-d4', title: 'Petroff: Early d4 Punished', level: 'Beginner', hero: 'b',
    tagline: 'Meet 3.d4 with ...exd4 and ...Ne4.',
    desc: 'White’s premature 3.d4? loses a pawn after ...exd4 and ...Ne4!, when the knight sits like a rock and e5 falls next.',
    ideas: ['3...exd4 opens the e-file with gain.', '4...Ne4! The outpost cannot be shifted.', 'White’s center was a bluff — develop instead.'],
    line: ['e2e4','e7e5','g1f3','g8f6','d2d4','e5d4','e4e5','f6e4','b1c3'],
    notes: { 7: '4...Ne4! The knight cannot be touched.' },
    drill: { afterPly: 7, moves: ['f6e4','b1c3'], about: 'Black to move: occupy e4!' } },
  { id: 'm-trap-muzio', title: 'Muzio Gambit Sacrifice', level: 'Advanced', hero: 'w',
    tagline: 'Sac the knight on move 5 for mate.',
    desc: 'The craziest sound gambit: 5.0-0! lets Black take the knight, and Qxf3-e5+ hunts the king across the board.',
    ideas: ['5.0-0! ignores the attacked knight.', 'Qxf3-e5+ starts the hunt.', 'Development beats material when kings are open.'],
    line: ['e2e4','e7e5','f2f4','e5f4','g1f3','g7g5','f1c4','g5g4','e1g1','g4f3','d1f3'],
    notes: { 8: '5.0-0! The Muzio — development over material.', 10: '6.Qxf3! The hunt begins.' },
    drill: { afterPly: 8, moves: ['e1g1','g4f3','d1f3'], about: 'White to play: sac into the Muzio!' } },
  { id: 'm-trap-budapest', title: 'Budapest: ...Qe7 Squeeze', level: 'Intermediate', hero: 'b',
    tagline: 'Win the gambit pawn back with ...Qe7.',
    desc: 'The Budapest’s point: after 5.Nf3 Bb4+ 6.Nbd2 Qe7, the e5-pawn cannot be held — ...Ngxe5 regains everything with equality.',
    ideas: ['5...Bb4+ forces the awkward Nbd2.', '6...Qe7! pins e5 to the king’s future.', '7...Ngxe5 levels material with activity.'],
    line: ['d2d4','g8f6','c2c4','e7e5','d4e5','f6g4','c1f4','b8c6','g1f3','f8b4','b1d2','d8e7','a2a3','g4e5','f3e5','c6e5'],
    notes: { 11: '6...Qe7! The squeeze — e5 is doomed.', 15: '8...Nxe5 levels up with tempo.' },
    drill: { afterPly: 13, moves: ['g4e5','f3e5'], about: 'Black to move: regain the pawn!' } },
  { id: 'm-trap-vienna-bc4', title: 'Vienna: 3.Bc4 Falls to ...d5', level: 'Beginner', hero: 'b',
    tagline: 'Punish early bishop sorties with ...d5.',
    desc: '3.Bc4?! invites 3...Nxe4! and after 4.Nxe4 d5! the fork wins a piece — opening principles with teeth.',
    ideas: ['3...Nxe4! removes the center guard.', '4...d5! Forks bishop and knight.', 'Develop knights before bishops — every time.'],
    line: ['e2e4','e7e5','b1c3','g8f6','f1c4','f6e4','c3e4','d7d5','f2f4'],
    notes: { 7: '4...d5! The fork wins material.' },
    drill: { afterPly: 7, moves: ['d7d5','f2f4'], about: 'Black to move: fork with ...d5!' } },
  { id: 'm-trap-schliemann', title: 'Schliemann: ...Qd5 Double Hit', level: 'Intermediate', hero: 'b',
    tagline: 'End the chaos with ...Qd5.',
    desc: 'The Schliemann’s madness resolves in Black’s favor: after all the captures, 7...Qd5! hits the knight on c6 and g2 at once.',
    ideas: ['Trade everything — the queen ends the debate.', '7...Qd5! Double attack decides.', 'Chaos favors the better-developed side.'],
    line: ['e2e4','e7e5','g1f3','b8c6','f1b5','f7f5','b1c3','f5e4','c3e4','d7d5','f3e5','d5e4','e5c6','d8d5','c6a7'],
    notes: { 13: '7...Qd5! Hits c6 and g2 — game over.' },
    drill: { afterPly: 13, moves: ['d8d5','c6a7'], about: 'Black to move: the double hit!' } },
  { id: 'm-trap-maxlange', title: 'Max Lange: Re1 Avalanche', level: 'Advanced', hero: 'w',
    tagline: 'Two pawns for a mating attack.',
    desc: 'The wildest sound gambit: White gives two pawns, and 8.Re1+! rips Black’s king to the center where it gets hunted.',
    ideas: ['6.e5! chases the knight with gain.', '7.exf6 opens the e-file by force.', '8.Re1+! The king walk begins.'],
    line: ['e2e4','e7e5','g1f3','b8c6','f1c4','g8f6','d2d4','e5d4','e1g1','f8c5','e4e5','d7d5','e5f6','d5c4','f1e1'],
    notes: { 10: '6.e5! Tempo after tempo.', 14: '8.Re1+! The hunt is on.' },
    drill: { afterPly: 10, moves: ['e4e5','d7d5','e5f6'], about: 'White to play: start the avalanche!' } },
  { id: 'm-trap-kg-qh4', title: "King's Gambit: ...Qh4+ Punishment", level: 'Beginner', hero: 'b',
    tagline: 'Meet fxe5 with ...Qh4+.',
    desc: 'Greedy 3.fxe5?? walks into 3...Qh4+! with a winning double attack — the first lesson of gambit discipline.',
    ideas: ['3...Qh4+! Checks and hits e4.', 'White’s center collapses at once.', 'Never grab pawns with the king exposed.'],
    line: ['e2e4','e7e5','f2f4','f8c5','f4e5','d8h4','e1e2'],
    notes: { 5: '3...Qh4+! Game over in one move.' },
    drill: { afterPly: 5, moves: ['d8h4','e1e2'], about: 'Black to move: punish the greed!' } },
  { id: 'm-trap-center-ng4', title: 'Center Game: ...Ng4 Double Attack', level: 'Beginner', hero: 'b',
    tagline: 'Punish 5.e5 with ...Ng4.',
    desc: '5.e5?? blocks the queen’s defense and 5...Ng4! hits e3 and f2 together — a two-move punishment every beginner must know.',
    ideas: ['5...Ng4! Hits queen and f2.', 'The e-pawn advance was a blunder.', 'Look for double attacks before “attacking” moves.'],
    line: ['e2e4','e7e5','d2d4','e5d4','d1d4','b8c6','d4e3','g8f6','e4e5','f6g4'],
    notes: { 9: '5...Ng4! Queen and f2 both hang.' },
    drill: { afterPly: 9, moves: ['f6g4','e3g3'], about: 'Black to move: the double attack!' } },
  { id: 'm-trap-italian-nxe4', title: 'Italian: ...Nxe4 Exploits the Pin', level: 'Intermediate', hero: 'b',
    tagline: 'Use the Bb4 pin to win e4.',
    desc: 'With White’s knight pinned by ...Bb4, 7...Nxe4! wins the center — the pin does the tactical work.',
    ideas: ['...Bb4 pins the c3-knight to the king.', '7...Nxe4! White cannot recapture.', 'Pins turn “solid” centers into targets.'],
    line: ['e2e4','e7e5','g1f3','b8c6','f1c4','f8c5','c2c3','g8f6','d2d4','e5d4','c3d4','c5b4','b1c3','f6e4','d4d5'],
    notes: { 13: '7...Nxe4! The pin makes it free.' },
    drill: { afterPly: 13, moves: ['f6e4','d4d5'], about: 'Black to move: win e4!' } },
];
